create table "order"
(
    id                   bigint generated by default as identity
        constraint pk_order
            primary key,
    user_id              bigint       not null,
    train_id             bigint       not null,
    departure_station_id bigint       not null,
    arrival_station_id   bigint       not null,
    status               integer      not null,
    seat                 varchar(255) not null,
    price                numeric      not null,
    points               integer      not null,
    created_at           timestamp,
    updated_at           timestamp
);

alter table "order"
    owner to postgres;


