create table route
(
    id          bigint generated by default as identity
        constraint pk_route
            primary key,
    name        varchar(255) not null
        constraint uc_route_name
            unique,
    station_ids bigint[],
    created_at  timestamp,
    updated_at  timestamp
);

alter table route
    owner to postgres;


