create table station
(
    id         bigint generated by default as identity
        constraint pk_station
            primary key,
    name       varchar(255) not null
        constraint uc_station_name
            unique,
    created_at timestamp,
    updated_at timestamp
);

alter table station
    owner to postgres;


