create table train
(
    id              bigint generated by default as identity
        constraint pk_train
            primary key,
    name            varchar(255) not null,
    route_id        bigint       not null,
    seats           boolean[]    not null,
    train_type      integer      not null,
    date            varchar(255) not null,
    arrival_times   date[]       not null,
    departure_times date[]       not null,
    extra_infos     text[]       not null,
    created_at      timestamp,
    updated_at      timestamp
);

alter table train
    owner to postgres;


