CREATE TABLE l23o6.user1
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255),
    phone      VARCHAR(255),
    type       VARCHAR(255),
    user_type INTEGER,
    idn        VARCHAR(255),
    points     INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user1 PRIMARY KEY (id)
);

ALTER TABLE l23o6.user1
    ADD CONSTRAINT uc_user1_username UNIQUE (username);